### ISSUE TITLE
Listings get doubled in display list

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-market#275]
Win64, Alpha release version. 

Reproduction Steps: Go to Sell tab. Click on a listing to open additional info. Click the red X for deleting it. Click yes. (you get a toast saying you can't delete, but that's not the issue I'm reporting). Then close modal by clicking off it. I now see my items shown twice in my listings list.

Severity - minor. Leaving the Sell tab and coming back returns the list to normal so it is just a display issue not a data issue.

![image](https://user-images.githubusercontent.com/38863166/40798618-1a229478-64d1-11e8-9219-0bbeb712c535.png)

**Comment by kewde** [comment]
Post issues with the desktop to https://github.com/particl/particl-desktop
