### ISSUE TITLE
particl-desktop-1.2.2-20181128-alpha-RC1-win-x64 unable to click 'Accept terms'

### ISSUE THREAD

**Issue by ezoer** [particl/particl-market#339]
When starting Particl Desktop, I'm prompted to click Accept or Decline and Close. The Accept button remains greyed out even if I'm scrolling to the end of the terms and conditions. See image:

![tandcs](https://user-images.githubusercontent.com/2060048/49606261-2a4d0700-f993-11e8-95b4-888277c4f966.png)

**Comment by zaSmilingIdiot** [comment]
It might be better to log this over at https://github.com/particl/particl-desktop/issues as this is actually a desktop client issue and does not have anything specifically particl-market related.
