### ISSUE TITLE
Flagged items coming back with error.  It says "there was an error in flagging this item"  

### ISSUE THREAD

**Issue by chunkingcheese** [particl/particl-market#448]
It could be me.  I am not a computer guy.

**Comment by xludx** [comment]
This could also be an issue in the gui, but I'll check it out. Can you provide any more information, like hash of he item?

**Comment by chunkingcheese** [comment]
No.  I don't know what a hash is.  I just tried to do it again, and the problem seems to have gone away.  I wonder if it had to do with my lack of anon coins or coin maturation.

**Comment by zaSmilingIdiot** [comment]
The error mentioned is a GUI related one, and occurs when the creation of the item flag proposal fails. Which, if there are no other marketplace errors (such as errors related to using different wallets, etc with the same marketplace DB), typically indicates that there are insufficient funds to create the flagged item proposal.
