### ISSUE TITLE
It appears as if I bought every item on the market, with a zero balance

### ISSUE THREAD

**Issue by chunkingcheese** [particl/particl-market#453]
I bought these while it was still loading.  When I shut the wallet down, it went all the way back to sync from beginning, and went from zero to 100%.  I did not expect the wallet to resync from the beginning.  
![image](https://user-images.githubusercontent.com/53626255/62408384-37031880-b57d-11e9-9c78-cd452d090e7f.png)

![snip2](https://user-images.githubusercontent.com/53626255/62408400-792c5a00-b57d-11e9-9a78-80a03e2bdc7f.JPG)

**Comment by xludx** [comment]
gui issue
