### ISSUE TITLE
Images on the marketplace missing

### ISSUE THREAD

**Issue by Arantuil** [particl/particl-market#481]
As you can see in this image, all the listing images are not displaying as well as the images in "orders" and "listings" under the "sell" tab: https://imgur.com/XWCC1Jr
But all the images are in my "AppData\Roaming\particl-market\images" folder   https://imgur.com/rA4LE3p
Also, a sell order has been marked as completed by the buyer, but for me it still shows "shipping". But I do have received the escrow amount.

**Comment by xludx** [comment]
gui issues
